default_language_version:
  node: 24.2.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      # Only enforce branch naming, not commit messages (since we validate PR titles instead)
      - id: commitizen-branch
        stages: [pre-push]

  # Ruff version.
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.12.0"
    hooks:
      # Run the linter.
      - id: ruff
        exclude: "tests/legacy"
        args: ["--fix"]
      # Run the formatter
      - id: ruff-format
        exclude: "tests/legacy"

  # python static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.16.1"
    hooks:
      - id: mypy
        additional_dependencies: [types-PyYAML, types-setuptools]
        exclude: "tests"

  # add bandit for security checks
  # semgrep does not support Windows, therefore it is not currently used in pre-commit
  # https://github.com/semgrep/semgrep/issues/1330
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.5
    hooks:
      - id: bandit
        args:
          [
            "-c",
            "pyproject.toml",
            "--severity-level",
            "medium",
            "--confidence-level",
            "high",
          ]
        additional_dependencies: ["bandit[toml]"]

  # notebooks.
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-ruff
        # Ignore unsorted imports. This is because jupyter notebooks can import
        # packages in a different order than the rest of the codebase.
        args: ["--ignore=D100,D407,I001,E402"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint

  # zizmor detects security issues in GitHub Actions workflows.
  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.9.0
    hooks:
      - id: zizmor
        args: ["--min-severity", "medium", "--min-confidence", "high"]
