# Semgrep Scanner Action
#
# This composite action executes static analysis security testing using Semgrep,
# providing comprehensive code analysis capabilities.
#
# Key Features:
# - Multi-language support
# - Custom rule sets
# - Incremental scanning
# - SARIF reporting
# - Performance optimization
#
# Process Stages:
# 1. Environment Setup:
#    - Python installation
#    - Semgrep configuration
#    - Rule preparation
#
# 2. Scan Execution:
#    - Target selection
#    - Rule application
#    - Code analysis
#
# 3. Results Processing:
#    - Report generation
#    - Finding analysis
#    - Output formatting
#
# Required Inputs:
# - scan-scope: Files to scan
# - config: Rule configuration
# - severity: Issue threshold
#
# Outputs:
# - scan_result: Scan exit code
# - report_path: Results location
#
# Example Usage:
# steps:
#   - uses: ./.github/actions/security/semgrep
#     with:
#       scan-scope: "changed"
#       config: "p/owasp-top-ten"
#
# Note: Consider using custom rule sets for project-specific checks

name: "Semgrep SAST Scan"
description: "Runs Semgrep security scanner with configurable options"

inputs:
  scan-scope:
    description: "Scope of files to scan (all/changed)"
    required: false
    default: "changed"
  paths:
    description: "Paths to scan when using all scope"
    required: false
    default: "."
  config:
    description: "Semgrep rules or config to use"
    required: false
    default: "p/default p/cwe-top-25 p/trailofbits p/owasp-top-ten"
  severity:
    description: "Minimum severity level to report (LOW/MEDIUM/HIGH/CRITICAL)"
    required: false
    default: "LOW"
  timeout:
    description: "Maximum time to run semgrep in seconds"
    required: false
    default: "300"
  output-format:
    description: "Format for scan results (text/json/sarif)"
    required: false
    default: "sarif"
  fail-on-findings:
    description: "Whether to fail the action if issues are found"
    required: false
    default: "true"

outputs:
  scan_result:
    description: "Exit code of the Semgrep scan"
    value: ${{ steps.run-semgrep.outputs.exit_code }}
  report_path:
    description: "Path to the generated report file"
    value: ${{ steps.run-semgrep.outputs.report_path }}

runs:
  using: composite
  steps:
    - name: Get changed files
      if: inputs.scan-scope == 'changed'
      id: changed-files
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
      with:
        files: |
          **/*.*

    - name: Run Semgrep scan
      id: run-semgrep
      shell: bash
      # Set the SEMGREP_RULES environment variable to specify which rules Semgrep should use.
      env:
        SEMGREP_RULES: ${{ inputs.config }}
        INPUTS_SCAN_SCOPE: ${{ inputs.scan-scope }}
        INPUTS_PATHS: ${{ inputs.paths }}
        INPUTS_SEVERITY: ${{ inputs.severity }}
        INPUTS_TIMEOUT: ${{ inputs.timeout }}
        INPUTS_OUTPUT_FORMAT: ${{ inputs.output-format }}
        INPUTS_FAIL_ON_FINDINGS: ${{ inputs.fail-on-findings }}
      # zizmor ignore: all_changed_files is tj-actions/changed-files output
      run: | # zizmor: ignore[template-injection]
        set +e
        # Map standard severity levels to Semgrep's levels
        # Semgrep does not support hierarchy, levels must be set explicitly
        case "$INPUTS_SEVERITY" in
          "LOW")
            SEMGREP_SEVERITY="--severity INFO --severity WARNING --severity ERROR"
            ;;
          "MEDIUM")
            SEMGREP_SEVERITY="--severity WARNING --severity ERROR"
            ;;
          "HIGH"|"CRITICAL")
            SEMGREP_SEVERITY="--severity ERROR"
            ;;
          *)
            SEMGREP_SEVERITY="--severity WARNING --severity ERROR"
            ;;
        esac

        # Create results directory
        mkdir -p security-results/semgrep

        REPORT_FILE="security-results/semgrep/semgrep-results.$INPUTS_OUTPUT_FORMAT"

        if [[ "$INPUTS_SCAN_SCOPE" == "changed" && -n "${{ steps.changed-files.outputs.all_changed_files }}" ]]; then
          echo "Running Semgrep on changed files, output results into workflow log only"
          FILES="${{ steps.changed-files.outputs.all_changed_files }}"
        semgrep \
          ${SEMGREP_SEVERITY} \
          --error \
          --timeout "$INPUTS_TIMEOUT" \
          --metrics=off \
          ${FILES}
        exit_code="$?"
        echo "exit_code=$exit_code" >> $GITHUB_OUTPUT

        elif [[ "$INPUTS_SCAN_SCOPE" == "all" ]] ; then
          echo "Running Semgrep on all files in $INPUTS_PATHS"
        semgrep \
          ${SEMGREP_SEVERITY} \
          --error \
          --metrics=off \
          --timeout "$INPUTS_TIMEOUT" \
          --"$INPUTS_OUTPUT_FORMAT" \
          -o "${REPORT_FILE}" \
          "$INPUTS_PATHS"
        exit_code="$?"
        echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
        echo "report_path=${REPORT_FILE}" >> $GITHUB_OUTPUT

        else
          echo "No files to scan found"
        fi

        if [[ "$INPUTS_FAIL_ON_FINDINGS" == "true" && -n "$exit_code" && "$exit_code" != "0" ]]; then
          exit $exit_code
        fi

      # Upload results after full scope analysis
    - name: Upload reports
      if: hashFiles('security-results/semgrep/*') != '' # if any report is available
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: semgrep-results
        path: security-results/semgrep
        retention-days: 7
    - name: Upload sarif
      if: hashFiles('security-results/semgrep/semgrep-results.sarif') != '' # if SARIF is available, upload it
      uses: github/codeql-action/upload-sarif@51f77329afa6477de8c49fc9c7046c15b9a4e79d # v3.29.5
      with:
        sarif_file: security-results/semgrep/semgrep-results.sarif
